version: '2'

services:
  app:
    image: 'demo-crud:latest'
    build:
      context: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sapiens.postgres.database.azure.com/postgres
      - SPRING_DATASOURCE_USERNAME=sapiens
      - SPRING_DATASOURCE_PASSWORD=popopopopP0.
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080