name: Azure Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: sapienscontainer.azurecr.io
        username: sapienscontainer
        password: ylEhxsrslke0CypBzCxxXf3wKhrvFvy54xpVtEoJaG+ACRC7hCu1
    - run: docker build -t sapienscontainer.azurecr.io/todo-backend:latest .
    - run: docker push sapienscontainer.azurecr.io/todo-backend:latest

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: your-azure-app-service
        images: sapienscontainer.azurecr.io/todo-backend:latest
